import { FooterSection } from "@/components/layout/sections/footer";
import { Navbar } from "@/components/layout/navbar";

export default function PrivacyPolicyPage() {
    return (
        <div className="min-h-screen flex flex-col">
            <Navbar />

            <main className="flex-grow container mx-auto px-4 py-8 max-w-4xl">
                <div className="space-y-6">
                    <div className="text-center mb-8">
                        <h1 className="text-3xl font-bold mb-2">Privacy Policy</h1>
                        <p className="text-gray-600">Last Updated: April 5, 2025</p>
                    </div>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-semibold">1. Introduction</h2>
                        <p>At Reg-Guru, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our AI Document Q&A chatbot service. Please read this privacy policy carefully. If you do not agree with the terms of this privacy policy, please do not access the service.</p>
                        <p>We reserve the right to make changes to this Privacy Policy at any time and for any reason. We will alert you about any changes by updating the &quot;Last Updated&quot; date of this policy. You are encouraged to periodically review this Privacy Policy to stay informed of updates.</p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-semibold">2. Information We Collect</h2>

                        <h3 className="text-xl font-medium">2.1 Personal Information</h3>
                        <p>We may collect personal information that you voluntarily provide to us when you:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Register for an account</li>
                            <li>Sign up for our newsletter</li>
                            <li>Request customer support</li>
                            <li>Participate in promotions or surveys</li>
                        </ul>
                        <p>The personal information we collect may include:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Name</li>
                            <li>Email address</li>
                            <li>Phone number (optional)</li>
                            <li>Billing information</li>
                            <li>Company name (for business accounts)</li>
                            <li>Job title (optional)</li>
                        </ul>

                        <h3 className="text-xl font-medium">2.2 Document Data</h3>
                        <p>When you use our AI Document Q&A chatbot, we collect and process:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Documents you upload for analysis</li>
                            <li>Queries you submit to the Service</li>
                            <li>Responses generated by our AI</li>
                            <li>Usage patterns and interaction history</li>
                        </ul>

                        <h3 className="text-xl font-medium">2.3 Automatically Collected Information</h3>
                        <p>When you access our Service, we may automatically collect:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Device information (type, model, operating system)</li>
                            <li>IP address</li>
                            <li>Browser type and version</li>
                            <li>Usage statistics and session information</li>
                            <li>Log data (access times, pages viewed)</li>
                            <li>Cookies and similar tracking technologies</li>
                        </ul>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-semibold">3. How We Use Your Information</h2>
                        <p>We may use the information we collect from you for various purposes, including to:</p>

                        <h3 className="text-xl font-medium">3.1 Provide and Maintain the Service</h3>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Process and analyze your documents</li>
                            <li>Generate responses to your queries</li>
                            <li>Facilitate account creation and management</li>
                            <li>Process payments and transactions</li>
                            <li>Send administrative notifications</li>
                        </ul>

                        <h3 className="text-xl font-medium">3.2 Improve and Personalize the Service</h3>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Develop new features and functionality</li>
                            <li>Improve our AI models and algorithms</li>
                            <li>Personalize your experience</li>
                            <li>Monitor and analyze usage patterns and trends</li>
                            <li>Debug and troubleshoot technical issues</li>
                        </ul>

                        <h3 className="text-xl font-medium">3.3 Communications and Marketing</h3>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Respond to your inquiries and support requests</li>
                            <li>Send product updates and newsletters (with opt-out options)</li>
                            <li>Provide information about new features or services</li>
                            <li>Conduct surveys and collect feedback</li>
                        </ul>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-semibold">4. How We Handle Your Documents</h2>

                        <h3 className="text-xl font-medium">4.1 Document Storage and Security</h3>
                        <p>Documents you upload to Reg-Guru are stored securely in encrypted form. We implement appropriate technical and organizational measures designed to protect your documents from unauthorized access, disclosure, alteration, or destruction.</p>

                        <h3 className="text-xl font-medium">4.2 Document Processing</h3>
                        <p>When you upload documents, our AI systems process them to:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Extract relevant information for indexing and analysis</li>
                            <li>Create searchable content that can be queried</li>
                            <li>Generate responses based on document content</li>
                        </ul>
                        <p>This processing is necessary to provide the core functionality of our Service.</p>

                        <h3 className="text-xl font-medium">4.3 AI Training and Improvement</h3>
                        <p>Unless you explicitly opt out, we may use anonymized data derived from your documents to improve our AI models and algorithms. This helps us enhance the accuracy and capabilities of our Service. When used for training purposes, all identifying information is removed, and we apply strict security and privacy controls.</p>

                        <h3 className="text-xl font-medium">4.4 Document Retention</h3>
                        <p>We store your documents for as long as you maintain an active account with us, plus a reasonable period for backup and legal compliance purposes. You can delete your documents at any time through your account settings. Upon deletion, documents are removed from active systems within 30 days, though they may remain in backup systems for up to 90 days.</p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-semibold">5. Information Sharing and Disclosure</h2>
                        <p>We may share your information in the following circumstances:</p>

                        <h3 className="text-xl font-medium">5.1 Service Providers</h3>
                        <p>We may share your information with third-party vendors, service providers, contractors, or agents who perform services for us or on our behalf. These may include:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Cloud storage providers</li>
                            <li>Payment processors</li>
                            <li>Analytics services</li>
                            <li>Customer support tools</li>
                        </ul>
                        <p>These service providers are obligated to protect your information and are prohibited from using it for any purpose other than to provide the specific services we have requested.</p>

                        <h3 className="text-xl font-medium">5.2 Business Transfers</h3>
                        <p>If we are involved in a merger, acquisition, financing, reorganization, bankruptcy, or sale of company assets, your information may be transferred as part of that transaction. We will notify you of any such change in ownership or control of your personal information.</p>

                        <h3 className="text-xl font-medium">5.3 Legal Requirements</h3>
                        <p>We may disclose your information where required to do so by law or in the good faith belief that such action is necessary to:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Comply with a legal obligation</li>
                            <li>Protect and defend our rights or property</li>
                            <li>Prevent or investigate possible wrongdoing</li>
                            <li>Protect the personal safety of users or the public</li>
                            <li>Protect against legal liability</li>
                        </ul>

                        <h3 className="text-xl font-medium">5.4 With Your Consent</h3>
                        <p>We may share your information with your consent or at your direction.</p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-semibold">6. Data Security</h2>
                        <p>We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information and documents we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the Internet or information storage technology can be guaranteed to be 100% secure.</p>
                        <p>Our security measures include:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Encryption of sensitive data in transit and at rest</li>
                            <li>Access controls and authentication requirements</li>
                            <li>Regular security assessments and penetration testing</li>
                            <li>Employee training on data protection and security</li>
                            <li>Incident response procedures</li>
                        </ul>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-semibold">7. Your Privacy Rights</h2>

                        <h3 className="text-xl font-medium">7.1 Account Information</h3>
                        <p>You can review and change your personal information by logging into your account settings. You may also contact us directly to request access to, correct, or delete any personal information that you have provided to us.</p>

                        <h3 className="text-xl font-medium">7.2 Document Management</h3>
                        <p>You can view, download, and delete documents you have uploaded through your account dashboard. If you delete your documents, copies may remain viewable in cached and archived pages, or might have been copied or stored by other users.</p>

                        <h3 className="text-xl font-medium">7.3 Marketing Communications</h3>
                        <p>You can opt out of receiving marketing communications from us by clicking on the unsubscribe link in the emails we send, adjusting your communication preferences in your account settings, or by contacting us directly.</p>

                        <h3 className="text-xl font-medium">7.4 Cookies and Tracking Technologies</h3>
                        <p>Most web browsers are set to accept cookies by default. You can usually choose to set your browser to remove or reject cookies. Please note that such actions could affect certain features of our Service.</p>

                        <h3 className="text-xl font-medium">7.5 Data Protection Rights</h3>
                        <p>Depending on your location, you may have the following data protection rights:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>The right to access, update, or delete your personal information</li>
                            <li>The right to rectification if your information is inaccurate or incomplete</li>
                            <li>The right to object to our processing of your personal data</li>
                            <li>The right to request restriction of processing your personal information</li>
                            <li>The right to data portability</li>
                            <li>The right to withdraw consent</li>
                        </ul>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-semibold">8. Children&apos;s Privacy</h2>
                        <p>Our Service is not directed to children under the age of 13. We do not knowingly collect personal information from children under 13. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us so that we can take necessary actions.</p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-semibold">9. International Data Transfers</h2>
                        <p>Your information, including personal data, may be transferred to and maintained on computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those of your jurisdiction.</p>
                        <p>If you are located outside [Country] and choose to provide information to us, please note that we transfer the data, including personal data, to [Country] and process it there.</p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-semibold">10. Changes to This Privacy Policy</h2>
                        <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the &quot;Last Updated&quot; date at the top of this policy.</p>
                        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
                    </section>

                    <section className="space-y-4">
                        <h2 className="text-2xl font-semibold">11. Contact Us</h2>
                        <p>If you have any questions about this Privacy Policy, please contact us at:</p>
                        <p className="font-medium">privacy@reg-guru.com</p>
                        <p>By mail: [Your Company Address]</p>
                    </section>

                    <div className="border-t border-gray-200 pt-6 mt-8">
                        <p className="text-center text-gray-600 text-sm">
                            By using Reg-Guru, you acknowledge that you have read and understood this Privacy Policy and agree to its terms.
                        </p>
                    </div>
                </div>
            </main>

            <FooterSection />
        </div>
    );
}