import { FooterSection } from "@/components/layout/sections/footer";
import { Navbar } from "@/components/layout/navbar";

export default function TermsAndConditionsPage() {
    return (
        <div className="min-h-screen flex flex-col">
            <Navbar />

            <main className="flex-grow container mx-auto px-4 py-8 max-w-4xl">
                <div className="space-y-6">
                    <div className="text-center mb-8">
                        <h1 className="text-3xl font-bold mb-2">Terms and Conditions</h1>
                        <p className="text-gray-600">Last Updated: April 5, 2025</p>
                    </div>

                    <section id="introduction" className="space-y-4">
                        <h2 className="text-2xl font-semibold">1. Introduction</h2>
                        <p>Welcome to Reg-Guru, an AI-powered Document Q&A chatbot designed to help you extract information and answers from your regulatory documents. By accessing or using Reg-Guru, you agree to be bound by these Terms and Conditions (&quot;Terms&quot;). Please read them carefully.</p>
                        <p>If you do not agree with any part of these Terms, you may not access or use our services.</p>
                    </section>

                    <section id="definitions" className="space-y-4">
                        <h2 className="text-2xl font-semibold">2. Definitions</h2>
                        <ul className="list-disc pl-5 space-y-2">
                            <li><strong>&quot;Service&quot;</strong> refers to the Reg-Guru AI Document Q&A chatbot and all related features.</li>
                            <li><strong>&quot;User&quot;</strong> refers to any individual or entity that accesses or uses the Service.</li>
                            <li><strong>&quot;Documents&quot;</strong> refers to any files, texts, or other materials uploaded to or processed by the Service.</li>
                            <li><strong>&quot;Query&quot;</strong> refers to any question, prompt, or instruction submitted to the Service.</li>
                            <li><strong>&quot;Response&quot;</strong> refers to any output, answer, or information generated by the Service.</li>
                            <li><strong>&quot;We,&quot; &quot;Us,&quot; &quot;Our&quot;</strong> refers to the operators and owners of Reg-Guru.</li>
                        </ul>
                    </section>

                    <section id="service-usage" className="space-y-4">
                        <h2 className="text-2xl font-semibold">3. Service Usage</h2>
                        <h3 className="text-xl font-medium">3.1 Account Registration</h3>
                        <p>To use certain features of the Service, you may be required to register for an account. You agree to provide accurate information and keep your account credentials secure.</p>

                        <h3 className="text-xl font-medium">3.2 Document Upload</h3>
                        <p>The Service allows you to upload documents for analysis and querying. You are responsible for ensuring you have the right to upload and process these documents. We support common document formats including PDF, DOCX, TXT, and others as specified in our documentation.</p>

                        <h3 className="text-xl font-medium">3.3 Query Limitations</h3>
                        <p>Depending on your subscription tier, there may be limitations on the number of queries, document size, or processing time. These limitations are outlined in our pricing page and may be updated from time to time.</p>

                        <h3 className="text-xl font-medium">3.4 Acceptable Use</h3>
                        <p>When using Reg-Guru, you agree not to:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Upload documents containing malicious code or malware</li>
                            <li>Submit queries designed to generate harmful, illegal, or misleading information</li>
                            <li>Use the Service to circumvent legal or regulatory requirements</li>
                            <li>Attempt to reverse-engineer the AI models or algorithms</li>
                            <li>Share account access with unauthorized users</li>
                            <li>Use automated tools to access the Service beyond our published API limits</li>
                            <li>Upload documents containing personally identifiable information (PII) unless explicitly permitted by our data processing agreement</li>
                        </ul>
                    </section>

                    <section id="content-and-data" className="space-y-4">
                        <h2 className="text-2xl font-semibold">4. Content and Data</h2>
                        <h3 className="text-xl font-medium">4.1 Your Documents</h3>
                        <p>By uploading documents to Reg-Guru, you grant us a non-exclusive, worldwide license to use, store, and process these documents solely for the purpose of:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Providing Q&A functionality based on document content</li>
                            <li>Improving the accuracy and capabilities of our AI models</li>
                            <li>Maintaining and enhancing the Service</li>
                        </ul>
                        <p>You retain all ownership rights to your documents. We do not claim ownership of any documents you upload.</p>

                        <h3 className="text-xl font-medium">4.2 Document Confidentiality</h3>
                        <p>We understand that regulatory documents may contain sensitive information. We implement appropriate technical and organizational measures to protect your documents. Documents are processed in accordance with our Privacy Policy and any applicable data processing agreements.</p>

                        <h3 className="text-xl font-medium">4.3 Data Retention</h3>
                        <p>Your documents and queries may be stored for the duration of your account&apos;s active status, plus a reasonable period as required for backup and legal compliance purposes. You can request deletion of your documents at any time through your account settings.</p>
                    </section>

                    <section id="ai-responses" className="space-y-4">
                        <h2 className="text-2xl font-semibold">5. AI-Generated Responses</h2>
                        <h3 className="text-xl font-medium">5.1 Response Accuracy</h3>
                        <p>While Reg-Guru uses advanced AI technology to analyze documents and generate responses, we cannot guarantee that all responses will be completely accurate, comprehensive, or suitable for your specific needs. The Service is designed to assist with document navigation and information retrieval, not to replace professional judgment.</p>

                        <h3 className="text-xl font-medium">5.2 No Legal or Professional Advice</h3>
                        <p>Responses generated by Reg-Guru should not be considered legal, financial, or professional advice. All information provided should be verified with qualified professionals before making decisions based on the Service&apos;s outputs.</p>

                        <h3 className="text-xl font-medium">5.3 Response Ownership</h3>
                        <p>You may use the responses generated by Reg-Guru for your internal business purposes. However, you acknowledge that the underlying AI models, algorithms, and technologies remain our exclusive property.</p>
                    </section>

                    <section id="intellectual-property" className="space-y-4">
                        <h2 className="text-2xl font-semibold">6. Intellectual Property</h2>
                        <p>The Service, including its software, algorithms, user interface, and functionality, is owned by us and is protected by copyright, trademark, and other intellectual property laws.</p>
                        <p>You are granted a limited, non-exclusive, non-transferable license to use the Service in accordance with these Terms. This license does not include the right to:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Modify, adapt, or reverse engineer any part of the Service</li>
                            <li>Copy or create derivative works based on the Service</li>
                            <li>Use the Service to develop competing products or services</li>
                            <li>Remove, obscure, or alter any proprietary notices or labels</li>
                        </ul>
                    </section>

                    <section id="disclaimer" className="space-y-4">
                        <h2 className="text-2xl font-semibold">7. Disclaimer of Warranties</h2>
                        <p className="font-medium">THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND.</p>
                        <p>We specifically disclaim all warranties and conditions of any kind, whether express, implied, or statutory, including but not limited to:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>The accuracy, completeness, or reliability of document analyses and responses</li>
                            <li>The Service&apos;s suitability for regulatory compliance purposes</li>
                            <li>Uninterrupted or error-free operation of the Service</li>
                            <li>The Service&apos;s compatibility with your specific documents or needs</li>
                        </ul>
                        <p>You acknowledge that AI technology has inherent limitations and that responses may not always reflect the most current regulatory requirements or interpretations.</p>
                    </section>

                    <section id="liability" className="space-y-4">
                        <h2 className="text-2xl font-semibold">8. Limitation of Liability</h2>
                        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES RESULTING FROM:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Your use of or inability to use the Service</li>
                            <li>Reliance on information provided by the Service</li>
                            <li>Errors or inaccuracies in the Service&apos;s responses</li>
                            <li>Unauthorized access to your documents</li>
                            <li>Service interruptions or failures</li>
                        </ul>
                        <p>Our total liability for any claims arising from these Terms shall not exceed the amount paid by you, if any, for accessing the Service during the twelve (12) months preceding the claim.</p>
                    </section>

                    <section id="changes" className="space-y-4">
                        <h2 className="text-2xl font-semibold">9. Changes to Terms</h2>
                        <p>We reserve the right to modify these Terms at any time. We will provide notice of significant changes through the Service interface or via email. Your continued use of the Service after such modifications constitutes your acceptance of the updated Terms.</p>
                    </section>

                    <section id="termination" className="space-y-4">
                        <h2 className="text-2xl font-semibold">10. Termination</h2>
                        <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, for any reason, including a breach of these Terms.</p>
                        <p>Upon termination:</p>
                        <ul className="list-disc pl-5 space-y-2">
                            <li>Your right to use the Service will cease immediately</li>
                            <li>Your documents will be retained for a limited period as outlined in our data retention policy</li>
                            <li>You may request export of your documents prior to account closure</li>
                        </ul>
                        <p>All provisions of these Terms that by their nature should survive termination shall survive.</p>
                    </section>

                    <section id="governing-law" className="space-y-4">
                        <h2 className="text-2xl font-semibold">11. Governing Law</h2>
                        <p>These Terms shall be governed by and construed in accordance with the laws of [Your Jurisdiction], without regard to its conflict of law principles.</p>
                    </section>

                    <section id="contact" className="space-y-4">
                        <h2 className="text-2xl font-semibold">12. Contact Us</h2>
                        <p>If you have any questions about these Terms or our Service, please contact us at:</p>
                        <p className="font-medium">support@reg-guru.com</p>
                    </section>

                    <div className="border-t border-gray-200 pt-6 mt-8">
                        <p className="text-center text-gray-600 text-sm">
                            By using Reg-Guru, you acknowledge that you have read, understood, and agree to be bound by these Terms and Conditions.
                        </p>
                    </div>
                </div>
            </main>

            <FooterSection />
        </div>
    );
}