name: Reg-guru-backend

on:
  [workflow_dispatch, push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build image
        run: docker build ./backend -t uylulu/reg-guru-backend:latest

      - name: push image
        run: |
          docker push uylulu/reg-guru-backend:latest

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user
            docker pull uylulu/reg-guru-backend:latest
            docker stop reg-guru-backend || true
            docker rm reg-guru-backend || true
            docker run -d --name reg-guru-backend -p 500:500 uylulu/reg-guru-backend:latest
          
      
