name: Reg-guru-backend

on:
  [workflow_dispatch, push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build image
        run: docker build ./backend -t uylulu/reg-guru-backend:latest

      - name: push image
        run: |
          docker push uylulu/reg-guru-backend:latest
